services:
  intellical:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intellical-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - intellical-network

networks:
  intellical-network:
    driver: bridge
